dashboard/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = "dashboard"

urlpatterns = [
    path('dashboard',views.index ,name="index"),
    path('staff/',views.staff,name="staff"),
    path('product/',views.product , name="product"),
    path('order/',views.order, name="order"),
    path('product/delete/<int:pk>/',views.product_delete ,name="product_delete"),
    path('product/update/<int:pk>/',views.product_update ,name="product_update"),
    path('staff/detail/<int:pk>/',views.staff_detail ,name="staff_detail"),
]

inventoryproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dashboard.urls')),
    path('',include('user.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views as user_view
from django.contrib.auth import views as auth_views
app_name = "account"

urlpatterns = [
    path('register/',user_view.register,name="register"),
    path('',auth_views.LoginView.as_view(template_name="user/login.html") , name="login"),
    path('logout/',auth_views.LogoutView.as_view(template_name="user/logout.html"),name="logout"),
    path('profile/',user_view.profile , name="profile"),
    path('profile_update/',user_view.profile_update , name="update")
]

templates/partials/nav.html
 <!--Navbar-->
 <nav class="navbar navbar-expand-lg navbar-danger bg-danger">
    <div class="container">
        <a class="navbar-brand text-white" href="{% url 'dashboard:index' %}">Tipe Management System</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link text-white" href="{% url 'dashboard:index' %}">Dashboard <span
                            class="sr-only">(current)</span></a>
                </li>
            </ul>
            {% if user.is_authenticated %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link text-white" href="{% url 'account:profile' %}">{{ user.username }} Profile <span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'account:logout' %}">Logout</a>
                </li>
            </ul>
            {% else %}
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link text-white" href="{% url 'account:register' %}">Register<span
                            class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'account:login' %}">Login</a>
                </li>
            </ul>

            {% endif %}

        </div>
    </div>
</nav>
<!--End Navbar-->

templates/partials/topnav.html
<!--Topside-->
<div class="container">
    <div class="row mt-4">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    Information
                </div>
                <div class="card-body">
                    <marquee behavior="" direction="">
                        <h3 class="my-4">This is the Information</h3>
                    </marquee>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-dark text-white">
                    Statistics
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-4">
                            <a class="text-decoration-none text-dark" href="{% url 'dashboard:staff' %}">
                                <div class="card my-card shadow text-center p-3">
                                    <h4>Staff <i class="fas fa-users"></i></h4>
                                    <h3>{{ workers_count }}</h3>
                                </div>
                            </a>
                        </div>
                        <div class="col-md-4">
                            <a class="text-decoration-none text-dark" href="{% url 'dashboard:product' %}">
                                <div class="card my-card shadow text-center p-3">
                                    <h4>Products <i class="fas fa-box"></i></h4>
                                    <h3>4</h3>
                                </div>
                            </a>
                        </div>
                        <div class="col-md-4">
                            <a class="text-decoration-none text-dark" href="{% url 'dashboard:order' %}">
                                <div class="card my-card shadow text-center p-3">
                                    <h4>Orders <i class="fas fa-shipping-fast"></i></h4>
                                    <h3>4</h3>
                                </div>
                            </a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!--End Topside-->