dashboard/urls.py
from django.urls import path
from django.urls.resolvers import URLPattern
from . import views

app_name = "dashboard"

urlpatterns = [
    path('dashboard',views.index ,name="index"),
    path('staff/',views.staff,name="staff"),
    path('product/',views.product , name="product"),
    path('order/',views.order, name="order"),
    path('product/delete/<int:pk>/',views.product_delete ,name="product_delete"),
    path('product/update/<int:pk>/',views.product_update ,name="product_update"),
    path('staff/detail/<int:pk>/',views.staff_detail ,name="staff_detail"),
]

inventoryproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dashboard.urls')),
    path('',include('user.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views as user_view
from django.contrib.auth import views as auth_views
app_name = "account"

urlpatterns = [
    path('register/',user_view.register,name="register"),
    path('',auth_views.LoginView.as_view(template_name="user/login.html") , name="login"),
    path('logout/',auth_views.LogoutView.as_view(template_name="user/logout.html"),name="logout"),
    path('profile/',user_view.profile , name="profile"),
    path('profile_update/',user_view.profile_update , name="update")
]

dashboard/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

CATEGORY = (
    ('stationary','stationary'),
    ('Electronics','Electronics'),
    ('Food','Food'),
)

class Product(models.Model):
    name = models.CharField(max_length=25,null=True)
    category = models.CharField(max_length=25,choices=CATEGORY,null=True)
    quantity = models.PositiveBigIntegerField(null=True)

    class Meta:
        verbose_name_plural = 'Staff Product'

    def __str__(self):
        return f'{self.name} - {self.quantity}'


class Order(models.Model):
    product = models.ForeignKey(Product,on_delete= models.CASCADE,null=True)
    staff = models.ForeignKey(User,models.CASCADE,null=True)
    order_quantity = models.PositiveIntegerField(null=True)
    date = models.DateField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'Order'

    def __str__(self):
        return f'{self.product.name} orderd by {self.staff.username}'

dashboard/forms.py
from django import forms
from django.forms import fields
from .models import Product , Order

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = '__all__'

class OrderForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['product','order_quantity']

dashboard/views.py
from django.shortcuts import redirect, render
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from .models import Product , Order
from .forms import ProductForm ,OrderForm
from django.contrib.auth.models import User
from django.contrib import messages
# Create your views here.

@login_required(login_url = 'account:login')
def index(request):
    orders = Order.objects.all()
    products = Product.objects.all()
    workers_count = User.objects.all().count()
    if request.method == 'POST':
        form = OrderForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.staff= request.user
            post.save()
            return redirect('dashboard:index')
    else:
        form = OrderForm()

    context = {
        'orders': orders,
        'form': form,
        'products': products,
        'workers_count': workers_count
    }
    return render(request, 'dashboard/index.html', context)
    

@login_required(login_url = 'account:login')
def staff(request):
    workers = User.objects.all()
    workers_count = User.objects.all().count()
    
    context = {
        'workers': workers,
        'workers_count': workers_count,
    }
    
    return render(request, 'dashboard/staff.html', context)

@login_required(login_url = 'account:login')
def staff_detail(request, pk):
    worker = User.objects.get(id = pk)
    context = {
        'worker': worker
    }
    return render(request, 'dashboard/staff_detail.html', context) 

 
@login_required(login_url = 'account:login')
def product(request):
    count = 1
    items = Product.objects.all() # Using ORM
    # items = Product.objects.raw('SELECT * FROM dashboard_product')
    workers_count = User.objects.all().count()

    if request.method == 'POST':
        form = ProductForm(request.POST)

        if form.is_valid():
            form.save()
            product_name = form.cleaned_data.get('name')
            messages.success(request, f'{product_name} has been added!')
            
            return redirect(request.path)
    else:
        form = ProductForm()

    context = {
        'items':items,
        'form':form,
        'count':count,
        'workers_count': workers_count
    }
    return render(request , 'dashboard/product.html',context)



@login_required(login_url = 'account:login')
def product_delete(request , pk):
    item = Product.objects.get(id = pk)
    if request.method == 'POST':
        item.delete()
        return redirect("dashboard:product")
    return render(request , 'dashboard/product_delete.html')

@login_required(login_url = 'account:login')
def product_update(request , pk):
    item = Product.objects.get(id = pk)
    if request.method == "POST":
        form = ProductForm(request.POST , instance=item)

        if form.is_valid():
            form.save()
            return redirect ("dashboard:product")
    else:
        form = ProductForm(instance=item)
    context = {
        'form':form
    }
    return render(request , "dashboard/product_update.html",context)

@login_required(login_url = 'account:login')
def order(request):
    orders = Order.objects.all()
    workers_count = User.objects.all().count()
    context = {
        'orders':orders,
        'workers_count': workers_count,
    }
    return render(request , 'dashboard/order.html',context)

templates/dashboard/index.html
{% extends 'base.html' %}
{% block title %} Home page  {% endblock %}
{% block content %}

{% if user.is_authenticated and user.is_staff and user.is_superuser %}
{% include 'partials/topnav.html' %}

    <!--Graphs-->
    <div class="container">
        <div class="row my-5">
            <div class="col-md-6">
                <div class="bg-white">
                    <canvas id="myChart1" width="400" height="300"></canvas>
                    <script>
                        var ctx = document.getElementById('myChart1').getContext('2d');
                        var myChart1 = new Chart(ctx, {
                            type: 'pie',
                            data: {
                                labels: [{% for order in orders %} '{{ order.product.name }}' , {% endfor %}],
                                datasets: [{
                                    label: 'Products',
                                    data: [{% for order in orders %} {{ order.order_quantity }} , {% endfor %}],
                                    backgroundColor: [
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)'
                                    ],
                                    borderColor: [
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)'
                                    ],
                                    borderWidth: 1
                                }]
                            },
                            options: {
                                scales: {
                                    yAxes: [{
                                        ticks: {
                                            beginAtZero: true
                                        }
                                    }]
                                }
                            }
                        });
                    </script>
                </div>
            </div>
            <div class="col-md-6">
                <div class="bg-white">
                    <canvas id="myChart" width="400" height="300"></canvas>
                    <script>
                        var ctx = document.getElementById('myChart').getContext('2d');
                        var myChart = new Chart(ctx, {
                            type: 'bar',
                            data: {
                                labels: [{% for product in products %} '{{ product.name }}' , {% endfor %}],
                                datasets: [{
                                    label: 'Products',
                                    data: [{%for product in products %} {{ product.quantity }} , {% endfor %}],
                                    backgroundColor: [
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)'
                                    ],
                                    borderColor: [
                                        'rgba(255, 99, 132, 1)',
                                        'rgba(54, 162, 235, 1)',
                                        'rgba(255, 206, 86, 1)',
                                        'rgba(75, 192, 192, 1)',
                                        'rgba(153, 102, 255, 1)',
                                        'rgba(255, 159, 64, 1)'
                                    ],
                                    borderWidth: 1
                                }]
                            },
                            options: {
                                scales: {
                                    yAxes: [{
                                        ticks: {
                                            beginAtZero: true
                                        }
                                    }]
                                }
                            }
                        });
                    </script>
                </div>
            </div>
        </div>
    </div>
    <!--End Graphs-->
{% else %}
        {% include 'dashboard/staff_index.html' %}
{% endif %}
{% endblock %}

templates/dashboard/order.html
{% extends 'base.html' %}
{% block title %} Order page  {% endblock %}

{% block content %}

{% include 'partials/topnav.html' %}

<div class="container">
    <div class="row my-4">
        <div class="col-md-4">

        </div>
        <div class="col-md-8">
            <table class="table bg-white">
                <thead class="bg-info">
                    <tr class="text-white">
                        <th scope="col">#</th>
                        <th scope="col">Product</th>
                        <th scope="col">Category</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Order by</th>
                        <th scope="col">Date</th>
                    </tr>
                </thead>
                <tbody>
                    {% for order in orders %}
                        <tr>
                            <th scope="row">{{ order.id }}</th>
                            <td>{{ order.product.name }}</td>
                            <td>{{ order.product.category }}</td>
                            <td>{{ order.order_quantity }}</td>
                            <td>{{ order.staff.username }}</td>
                            <td>{{ order.date }}</td>
                        </tr>
                    {% endfor %}
                    
                </tbody>
            </table>
        </div>
    </div>

</div>
{% endblock %}

templates/dashboard/product.html
{% extends 'base.html' %}
{% block title %} Product Page  {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

{% include 'partials/topnav.html' %}

<div class="container">
    <div class="row my-4">
        <div class="col-md-4">
            {% for message in messages %}
            {% if message %}
                <div class="alert alert-{{message.tags}}" role="alert">
                    {{message.message}}
                </div>
            
            {% endif %}
            {% endfor %}
            <div class="border bg-white p-3">
                <h4>Add Products</h4>
                <hr>
                <form method="POST">
                    {% csrf_token %}
                    {{ form|crispy  }}
                    <input class="btn btn-success btn-block" type="submit" value="Add Product">

                </form>
            </div>
        </div>
        <div class="col-md-8">
            <table class="table bg-white">
                <thead class="bg-info">
                    <tr class="text-white">
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Category</th>
                        <th scope="col">Quantity</th>
                        <th scope="col">Activity</th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in items %}
                    <tr>
                        <th scope="row">{{forloop.counter}}</th>
                        <td>{{ item.name }}</td>
                        <td>{{ item.category }}</td>
                        <td>{{ item.quantity }}</td>
                        <td>
                            <a class="btn btn-info btn-sm" href="{% url 'dashboard:product_update' item.id %}">Edit</a>
                            <a class="btn btn-danger btn-sm" href="{% url 'dashboard:product_delete' item.id %}">Delete</a>
                        </td>
                    </tr>
                   {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

</div>


{% endblock %}

templates/dashboard/product_delete.html
{% extends 'base.html' %}
{% block title %} Delete Page  {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row mt-5">
        <div class="col-md-6 offset-md-3">
            <div class="border bg-white p-3">
                <h3>Delete Item</h3>
                <hr>
                <div class="alert alert-danger">
                    <h4>Are you sure you want to delete</h4>
                </div>
                <form method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <a class="btn btn-secondary" href="{% url 'dashboard:product' %}">Cancel</a>
                    <input type="submit" value="submit" class="btn btn-danger">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/dashboard/product_update.html
{% extends 'base.html' %}
{% block title %} Update Page  {% endblock %}
{% load crispy_forms_tags %}
{% block content %}

<div class="container">
    <div class="row mt-5">
        <div class="col-md-6 offset-md-3">
            <div class="border bg-white p-3">
                <h3>Update Product</h3>
                <hr>
                
                <form method="POST">
                    {% csrf_token %}
                    {{form|crispy}}
                    <a class="btn btn-secondary" href="{% url 'dashboard:product' %}">Update</a>
                    <input type="submit" value="submit" class="btn btn-info">
                </form>
            </div>
        </div>
    </div>
</div>

{% endblock %}

templates/dashboard/staff.html
{% extends 'base.html' %}
    {% block title %} 
        Staff Page
    {% endblock %}
{% block content %}

{% include 'partials/topnav.html' %}

<!--Table-->
<div class="container">
    <div class="row my-4">
        <div class="col-md-4"></div>
        <div class="col-md-8">
            <table class="table bg-white">
                <thead class="bg-info">
                    <tr class="text-white">
                        <th scope="col">#</th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th scope="col">Phone</th>
                    </tr>
                </thead>
                <tbody>
                    {% for worker in workers %}
                    <tr>
                        <th scope="row"><a class="btn btn-info btn-sm" href="{% url 'dashboard:staff_detail' worker.id %}">View</a></th>
                        <td>{{ worker.username }}</td>
                        <td>{{ worker.email }}</td>
                        <td>{{ worker.profile.phone }}</td>
                    </tr>
                    {% endfor %}
                 
                </tbody>
            </table>
        </div>
    </div>

</div>
    
{% endblock %}

templates/dashboard/staff_detail.html
{% extends 'base.html' %}
    {% block title %} 
        Staff Page
    {% endblock %}
{% block content %}

{% include 'partials/topnav.html' %}

<!--Table-->
<div class="container">
    <div class="row my-4">
        <div class="col-md-4"></div>
        <div class="col-md-8">
            <div class="container">
                <div class="row my-4">
                    <div class="col-md-4">
            
                    </div>
                    <div class="col-md-8">
                        <div class="card">
                            <div class="card-header bg-info text-white">
                                Profile Page
                            </div>
                            <div class="card-body">
                                <div class="row">
                                    <div class="col-md-8">
                                        <span class="h4"> Profile Information</span> 
                                        <hr>
                                        <table class="table bg-white table-borderless">
                                            <tbody>
                                                <tr>
                                                    <th scope="row">Name</th>
                                                    <td>{{ worker.username }}</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">Email</th>
                                                    <td>{{ worker.email }}</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">Phone</th>
                                                    <td>{{ worker.profile.phone }}</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">Address</th>
                                                    <td>{{ worker.profile.address }}</td>
                                                </tr>
                                            </tbody>
                                        </table>
            
                                    </div>
                                    <div class="col-md-4">
                                        <img class="img-thumbnail" src="{{ worker.profile.image.url }}" alt="">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
            
                </div>
            
            </div>
        </div>
    </div>

</div>
    
{% endblock %}

templates/dashboard/staff_index.html
{% load crispy_forms_tags %}
<div class="container">
    <div class="row mt-4">
        <div class="col-md-4">
            <div class="card">
                <div class="card-header">
                    Make Request
                </div>
                <div class="card-body">
                    <form method="POST">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <input class="btn btn-info btn-block" type="submit" value="Make Request">
                    </form>
                </div>
            </div>
        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">
                    Orders Records
                </div>
                <div class="card-body">
                    <table class="table bg-white">
                        <thead class="bg-info text-white">
                            <tr>
                                <th scope="col">Product</th>
                                <th scope="col">Category</th>
                                <th scope="col">Quantity</th>
                                <th scope="col">Date</th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for order in orders %}
                            {% if order.staff == user %}
                            <tr>
                                <td>{{order.product.name}}</td>
                                <td>{{ order.product.category }}</td>
                                <td>{{ order.order_quantity }}</td>
                                <td>{{ order.date }}</td>
                            </tr>
							{% endif %}
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>