inventoryproject/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('dashboard.urls')),
    path('',include('user.urls'))
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path
from . import views as user_view
from django.contrib.auth import views as auth_views
app_name = "account"

urlpatterns = [
    path('register/',user_view.register,name="register"),
    path('',auth_views.LoginView.as_view(template_name="user/login.html") , name="login"),
    path('logout/',auth_views.LogoutView.as_view(template_name="user/logout.html"),name="logout"),
    path('profile/',user_view.profile , name="profile"),
    path('profile_update/',user_view.profile_update , name="update")
]

user/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class profile(models.Model):
    staff = models.OneToOneField(User,on_delete=models.CASCADE, null=True)
    address = models.CharField(max_length=200 , null=True)
    phone = models.CharField(max_length=20, null=True , unique=True)
    image = models.ImageField(default = 'avatar.jpg', upload_to = 'Profile_Images')

    def __str__(self):
        return f'{self.staff.username}-Profile'
    class Meta:
        verbose_name_plural = 'Staff Profile'

user/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.db import models
from django.forms import fields
from .models import profile

class CreateUserForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ('username','email','password1','password2')

class UserUpadateForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ('username','email')

class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = profile
        fields = ['address','phone','image']

user/views.py
from django.shortcuts import render , redirect
from django.contrib.auth.forms import UserCreationForm
from .forms import CreateUserForm , UserUpadateForm , ProfileUpdateForm
from user import forms
from django.contrib import messages
# Create your views here.

def register(request):

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid:
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request , f'Account created for {username}')
            return redirect('account:login')
    else:
        form = CreateUserForm()
    
    context = {
        'form':form
    }

    return render(request,'user/register.html' ,context)


def profile(request):
    return render(request , 'user/profile.html')

def profile_update(request):
    if request.method == 'POST':
        user_form = UserUpadateForm(request.POST , instance=request.user)
        profile_form = ProfileUpdateForm(request.POST ,request.FILES , instance=request.user.profile)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            return redirect('account:profile')

    else:
        user_form = UserUpadateForm( instance=request.user)
        profile_form =  ProfileUpdateForm( instance = request.user.profile)
    context = { 
        'user_form':user_form,
        'profile_form':profile_form,
    }

    return render(request , "user/profile_update.html", context)

templates/user/login.html
{% extends 'base.html' %}

{% block title %} Login Page {% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-6 offset-md-3">
                {% for message in messages %}
                {% if message %}
                    <div class="alert alert-{{message.tags}}" role="alert">
                        {{message.message}}
                    </div>
                
                {% endif %}
                {% endfor %}
                <div class="border p-3">
                    <h3>Login page</h3>
                    <hr>
                    <form action="" method="POST">
                        {% csrf_token %}

                        {{form|crispy}}

                        <input class="btn btn-success" type="submit" value="Login">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/user/logout.html
{% extends 'base.html' %}

{% block title %} Logout Page {% endblock %}

<!-- {% load crispy_forms_tags %} -->

{% block content %}
<div class="container">
    <div class="row mt-5">
        <div class="col-md-6 offset-md-3">
            <div class="border p-3 bg-white">
                <h3>Logout page</h3>
                <hr>
               <div class="alert alert-danger">
                  
                   <h4>You have been loged out</h4>
               </div>
               <a href="{% url 'account:login' %}" class="btn btn-success">Login</a>
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/user/profile.html
{% extends 'base.html' %}

{% block title %} Profile Page {% endblock %}

{% load crispy_forms_tags %}


{% block content %}
<div class="container">
    <div class="row my-4">
        <div class="col-md-4">

        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-info text-white">
                    Profile Page
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <span class="h4"> Profile Information</span> <a class="btn btn-info btn-sm float-right"
                                href="{% url 'account:update' %}">Edit</a>
                            <hr>
                            <table class="table bg-white table-borderless">
                                <tbody>
                                    <tr>
                                        <th scope="row">Name</th>
                                        <td>{{ user.username }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Email</th>
                                        <td>{{ user.email }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Phone</th>
                                        <td>{{ user.profile.phone }}</td>
                                    </tr>
                                    <tr>
                                        <th scope="row">Address</th>
                                        <td>{{ user.profile.address }}</td>
                                    </tr>
                                </tbody>
                            </table>

                        </div>
                        <div class="col-md-4">
                            <img class="img-thumbnail" src="{{ user.profile.image.url }}" alt="">
                        </div>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

templates/user/profile_update.html
{% extends 'base.html' %}

{% block title %} Profile Page {% endblock %}

{% load crispy_forms_tags %}


{% block content %}
<div class="container">
    <div class="row my-4">
        <div class="col-md-4">

        </div>
        <div class="col-md-8">
            <div class="card">
                <div class="card-header bg-info text-white">
                    Profile Page
                </div>
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-8">
                            <span class="h4"> Profile Information</span>
                            <hr>
                           
                                <form action="" method="POST" enctype="multipart/form-data">
                                    {% csrf_token %}
                                    {{ user_form|crispy }}
                                    {{ profile_form|crispy }}
                                    <input type="submit" value="update" class="btn btn-info">
                                </form>
                        </div>
                        
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>
{% endblock %}

templates/user/register.html
{% extends 'base.html' %}

{% block title %} Register Page {% endblock %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="container">
        <div class="row mt-5">
            <div class="col-md-6 offset-md-3">
                {% for message in messages %}
                {% if message %}
                    <div class="alert alert-{{message.tags}}" role="alert">
                        {{message.message}}
                    </div>
                
                {% endif %}
                {% endfor %}
                <div class="border p-3">
                    <h3>Registration page</h3>
                    <hr>
                    <form action="" method="POST">

                        {% csrf_token %}
                        {{form|crispy}}
                        <input class="btn btn-success" type="submit" value="Register">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}